# Drafting an example output from the export.

services:
  itch_linux:
    image: starriver.run/gobbo
    volumes:
      - $GODOT:/opt/godot-$GODOT_VERSION:ro
      - $EXPORT_TEMPLATES:/root/.local/share/godot/export_templates:ro
      - $SRC:/srv/src:ro
      - $DIST:/srv/dist:z
    environment:
      SCRIPT_PRE: "echo pre"
      SCRIPT_POST: "echo post"
  itch_windows:
    {}
    # ...
  steam_linux:
    {}
    # ...
  steam_windows:
    {}
    # ...
