# Drafting an example output from the export.

services:
  itch_linux:
    image: _gobbo:latest
    volumes:
      - ./src:/srv/src:z,ro
      - ./dist:/srv/dist:z
    environment:
      SCRIPT_PRE: "echo pre"
      SCRIPT_POST: "echo post"
  itch_windows:
    {}
    # ...
  steam_linux:
    {}
    # ...
  steam_windows:
    {}
    # ...
